apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1h
  targetNamespace: wetfish-monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-stack-values
      valuesKey: values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1h
  targetNamespace: wetfish-monitoring
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1h
  targetNamespace: wetfish-monitoring
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
      valuesKey: values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1h
  targetNamespace: wetfish-monitoring
  install:
    remediation:
      retries: 3
    timeout: 5m
  upgrade:
    remediation:
      retries: 3
    timeout: 5m
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values
      valuesKey: values.yaml
---
# ConfigMaps wrapping existing Helm values files for HelmRelease valuesFrom
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-values
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/infrastructure/monitoring-values
  prune: true
