apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: staging-auto-update
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@wetfish.net
      messageTemplate: |
        chore(staging): auto-update images

        {{range .Changed.Changes}}
        - {{print .OldValue}} -> {{print .NewValue}}
        {{end}}
    push:
      branch: main
  update:
    path: ./services
    strategy: Setters
