apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: wetfish-dev
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "500m"
    defaultRequest:
      memory: "64Mi"
      cpu: "50m"
    type: Container
