apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wetfish-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@wetfish.net
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik
