apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home
  namespace: flux-system
spec:
  interval: 10m
  path: ./services/home/k8s/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: home-web
      namespace: wetfish-prod
  timeout: 5m
  dependsOn:
    - name: infrastructure
