FROM docker.io/node:14 AS npm

COPY ./src/public_html /public_html

RUN set -exu \
  && cd /public_html \
  && npm install

FROM docker.io/nginx:1.25-alpine

COPY --from=npm /public_html /var/www

RUN set -exu \
  && chown -R nginx:nginx /var/www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
